#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Submit URLs to IndexNow (Bing, Yandex and other participating engines).

Run this AFTER the site is deployed. It does nothing to the site itself.

    # see what would be sent, without sending
    python tools/indexnow-submit.py --dry-run

    # submit every URL in sitemap.xml
    python tools/indexnow-submit.py

    # submit only specific URLs (the normal case once set up)
    python tools/indexnow-submit.py --url https://icenmedical.com/about.html

Rules of thumb from Microsoft:
  * submit only URLs that were added, updated or deleted
  * do NOT submit unchanged URLs again, and never submit noindex pages
  * a submission is a discovery hint, not a guarantee of indexing

Requires: the key file must already be live at https://icenmedical.com/<KEY>.txt
"""
import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request

HOST = "icenmedical.com"

# Two key files are hosted on the site; each file's content is exactly its own
# filename (that is how IndexNow verifies ownership):
#
#   KEY     - the original key, self-generated by the site owner and live since
#             2026-09-18. This is the default for submissions and it works.
#   WMT_KEY - generated by Bing Webmaster Tools' IndexNow guide on 2026-09-28.
#             BWT offers no field for registering an existing key, so hosting the
#             key it generated is the only way to reach the IndexNow dashboard.
#             Pass it with --key once its file is deployed, so BWT can attribute
#             the submissions to the property.
KEY = "dcdae902ab0cd92247669e8df6eb42a3"
WMT_KEY = "eab38a1bd7a3455ab748fc6f7a80d1c9"
ENDPOINT = "https://api.indexnow.org/indexnow"


def key_location(key):
    return f"https://{HOST}/{key}.txt"
SITEMAP = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "sitemap.xml")

# 200 ok | 400 bad request | 403 key not valid | 422 url/host mismatch | 429 rate limited
EXPLAIN = {
    200: "OK - URLs submitted",
    202: "Accepted - key validation pending",
    400: "Bad request - invalid format",
    403: "Forbidden - key not valid (key file missing, or the file does not contain the key)",
    422: "Unprocessable - URLs do not belong to this host, or the key does not match the schema",
    429: "Too many requests - potential spam; slow down",
}


def urls_from_sitemap(path):
    with open(path, encoding="utf-8") as fh:
        return re.findall(r"<loc>(.*?)</loc>", fh.read())


def submit(urls, key, timeout=30):
    payload = json.dumps({
        "host": HOST,
        "key": key,
        "keyLocation": key_location(key),
        "urlList": urls,
    }).encode("utf-8")
    req = urllib.request.Request(
        ENDPOINT, data=payload,
        headers={"Content-Type": "application/json; charset=utf-8"},
        method="POST")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.status, resp.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode("utf-8", "replace")
    except Exception as e:                                  # noqa: BLE001
        return None, f"{type(e).__name__}: {e}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", action="append", default=[],
                    help="submit this URL (repeatable). Default: every URL in sitemap.xml")
    ap.add_argument("--dry-run", action="store_true", help="print the payload, send nothing")
    ap.add_argument("--limit", type=int, default=10000, help="max URLs (IndexNow cap is 10000)")
    ap.add_argument("--key", default=KEY,
                    help=f"key to submit with (default {KEY}); "
                         f"pass {WMT_KEY} once its key file is deployed to align "
                         f"submissions with Bing Webmaster Tools")
    args = ap.parse_args()

    key = args.key
    urls = args.url or urls_from_sitemap(SITEMAP)
    urls = urls[:args.limit]

    print(f"host         : {HOST}")
    print(f"key          : {key}")
    print(f"keyLocation  : {key_location(key)}")
    print(f"endpoint     : {ENDPOINT}")
    print(f"urls         : {len(urls)}")
    for u in urls[:8]:
        print(f"   {u}")
    if len(urls) > 8:
        print(f"   ... +{len(urls) - 8} more")

    if args.dry_run:
        print("\n[dry-run] nothing sent.")
        return 0

    print("\nsubmitting ...")
    status, body = submit(urls, key)
    print(f"  HTTP {status}: {EXPLAIN.get(status, 'unexpected status')}")
    if body.strip():
        print(f"  body: {body.strip()[:500]}")
    if status == 200:
        print("\nDone. Confirm receipt under Bing Webmaster Tools -> IndexNow.")
        return 0
    if status == 403:
        print(f"\nCheck that {key_location(key)} is live and its body is exactly the key.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
